app:
  api:
    title: SpringFlix API
    version: 1
  services:
    webui: http://localhost:9000
    movies: http://localhost:8081
    posters: http://localhost:8082
    trailers: http://localhost:8083

spring:
  application:
    name: springflix-gateway
  cloud:
    gateway:
      routes:
      - id: api_movies
        uri: ${spring.cloud.discovery.client.simple.instances.springflix-movies.0.uri}
        predicates:
        - Path=/api/v1/movies/**
        filters:
        - name: CircuitBreaker
          args:
            name: circuitBreakerMovies
            fallbackUri: forward:/fallback/movies/upcoming
            statusCodes:
            - 500
            - 404
      - id: api_posters
        uri: ${spring.cloud.discovery.client.simple.instances.springflix-posters.0.uri}
        predicates:
        - Path=/api/v1/posters/**
        filters:
        - name: CircuitBreaker
          args:
            name: circuitBreakerPosters
            fallbackUri: forward:/fallback/poster-not-found.png
            statusCodes:
            - 500
            - 404
      - id: api_trailers
        uri: ${spring.cloud.discovery.client.simple.instances.springflix-trailers.0.uri}
        predicates:
        - Path=/api/v1/trailers/**
      - id: main_page
        uri: ${spring.cloud.discovery.client.simple.instances.springflix-webui.0.uri}
        predicates:
        - Path=/main.html
        filters:
        - RewritePath=/main.html,/index.html
        - name: CircuitBreaker
          args:
            name: circuitBreakerWebUI
            fallbackUri: forward:/fallback/maintenance.html
      - id: webui
        uri: ${spring.cloud.discovery.client.simple.instances.springflix-webui.0.uri}
        predicates:
        - Path=/**
        filters:
        - name: CircuitBreaker
          args:
            name: circuitBreakerWebUI
            fallbackUri: forward:/fallback/maintenance.html
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
    discovery:
      client:
        simple:
          instances:
            springflix-webui:
            - uri: ${app.services.webui}
            springflix-movies:
            - uri: ${app.services.movies}
            springflix-posters:
            - uri: ${app.services.posters}
            springflix-trailers:
            - uri: ${app.services.trailers}

server:
  port: ${PORT:8080}

management:
  observations:
    key-values: &tags
      application: ${spring.application.name}
      service: ${spring.application.name}
      source: ${spring.application.name}-${random.uuid}
  metrics:
    tags: *tags
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        step: 30s
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    io:
      micrometer:
        registry:
          otlp: off
      opentelemetry:
        exporter:
          internal:
            http: off
