apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: springflix-services
spec:
  serviceAccountName: springflix-services-reader
  inputResources:
  - name: gateway
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springflix
  - name: movies
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springflix-movies
  - name: trailers
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springflix-trailers
  - name: posters
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springflix-posters
  - name: webui
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: springflix-webui
  template:
    type: Opaque
    stringData:
      app.services.webui: $(.webui.status.url)
      app.services.movies: $(.movies.status.url)
      app.services.posters: $(.posters.status.url)
      app.services.trailers: $(.trailers.status.url)
      app.services.gateway: $(.gateway.status.url)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: springflix-services-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: springflix-services-reader
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: springflix-services-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: springflix-services-reader
subjects:
- kind: ServiceAccount
  name: springflix-services-reader
