#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: springflix-config
type: Opaque
stringData:
  provider: sample
  type: config
  app.cache.ttl: 60m
  app.tmdb.api.key: #@ data.values.tmdb_api_key
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: springflix-config
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: springflix-config
