apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: springflix
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: springflix
spec:
  source:
    git:
      url: https://github.com/alexandreroman/springflix.git
      ref:
        branch: main
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      memory: 1Gi
  params:
  - name: annotations
    value:
      sidecar.opentelemetry.io/inject: "true"
      autoscaling.knative.dev/minScale: "0"
      autoscaling.knative.dev/maxScale: "3"
      autoscaling.knative.dev/target: "30"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/window: "300s"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: /api/openapi
      owner: default/default-team
      system: default/springflix
      description: SpringFlix API
  env:
  - name: SPRING_CONFIG_IMPORT
    value: optional:configtree:/${SERVICE_BINDING_ROOT}/config/
  - name: APP_SERVICES_WEBUI
    valueFrom:
      secretKeyRef:
        name: springflix-services
        key: app.services.webui
  - name: APP_SERVICES_MOVIES
    valueFrom:
      secretKeyRef:
        name: springflix-services
        key: app.services.movies
  - name: APP_SERVICES_POSTERS
    valueFrom:
      secretKeyRef:
        name: springflix-services
        key: app.services.posters
  - name: APP_SERVICES_TRAILERS
    valueFrom:
      secretKeyRef:
        name: springflix-services
        key: app.services.trailers
  serviceClaims:
  - name: config
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: springflix-config
