apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springflix-movies
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=springflix-movies
spec:
  type: service
  lifecycle: experimental
  owner: springflix-team
  system: springflix
  dependsOn:
  - resource:springflix-cache
