apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springflix
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=springflix
spec:
  type: service
  lifecycle: experimental
  owner: springflix-team
  system: springflix
  dependsOn:
  - component:springflix-webui
  - component:springflix-movies
  - component:springflix-posters
  - component:springflix-trailers
  providesApis:
  - springflix
